steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - "VUE_APP_URL=${_VUE_APP_URL}"
    - "VUE_APP_URL_ABSOLUTE=${_VUE_APP_URL_ABSOLUTE}"
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
